# config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm

  mappings:
    poster_file:
      # alias qui nous permet d'accéder à nos images depuis le navigateur
      uri_prefix: /uploads
      # Chemin vers le dossier de stockage
      upload_destination: '%upload_directory%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer