# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # For test mysql
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: checks_directory
        run: |
          if [ -d "./.idea" ]; then echo "Forbidden PHPStorm folder (.idea/) found ! Please, ignore in .gitignore"; exit 2; fi
          if [ -d "./.vscode" ]; then echo "Forbidden VScode folder (.vscode) found ! Please, ignore in .gitignore"; exit 2; fi
          if [ $(find ./ -name .DS_Store) ]; then echo "Forbidden MacOS boring file (.DS_Store) found ! Please, ignore in .gitignore"; exit 2; fi
          if [ -d "./vendor" ]; then echo "Forbidden external libs folder (vendor/) found !"; exit 2; fi

      - name: Composer
        run: composer install

      - name: Yarn
        run: yarn --ignore-engines install

      - name: code_quality
        run: |
          ./vendor/bin/phpcs
          ./vendor/bin/phpstan analyse src --level max
          ./vendor/bin/phpmd src text phpmd.xml
          ./bin/console lint:twig templates
          ./node_modules/.bin/eslint assets
          ./node_modules/.bin/sass-lint -c sass-linter.yml -v

      - name: phpunit
        # for test mysql
        run: |
          php ./bin/console doctrine:database:drop --if-exists --force || true
          php ./bin/console doctrine:database:create
          php ./bin/console doctrine:migrations:migrate -n
          php ./bin/console doctrine:fixtures:load -n
          yarn encore dev
          php ./vendor/bin/phpunit
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/tests
